# Developing  Deep learning Models use Pytorch.nn.Moudule for beginners
Here you will see how to build your own model using pytorch. We will start from the simplest to most complicated deep learning. There is a list of models we will cover in this tutorial. We only cover the programming here, if you are not familiar with the fundemetal of any of these you can easily search through internets.

1. Regrassion
2. Logistic Regression
3. Customized Artificial Neural Network
4. Recurrent Neural Network (Simple RNN, and LSTM)
5. Convolution Neural Netwrk

If you are familiar with Pytorch, you definitly know nn. Moudule Class enables programmer to build their customized model easily. You might think Keras is easier to work, but you will be suprised about the user firendly interface Pytorch is providing. In additon, when you can customised your model, you can build model combined two deep neural network together. For instance, think about predicting stock using RNN, you might think other features like weekday would effect the stock price, so, you can build model to combine classifer resutl with RNN result and make prediction!! Do you think is it amazing, let start learning how to build the Pytorch model as easy as Keras.

# 1.Regression
Regression is the simplest Artificial neural networks which transfers input_size=1 to output_size=1. To define the pytorch model, first you define the class name.
Here we call it <b>LinearReg</b>. Then we define the <b>__init__</b> function with the inputs. Then, then just use <b>super(linearRegression, self).__init__()</b>.

<img src='Image/Reg.PNG' align="center"/> 


These coding are the same for building all models. Now, you can build all layer you want here using torch.nn. Here, the order of the layer does not matter, so, just add as much as layer you want. For the regression, We only need one Linear transformation. All the class you define, has two parts, first the <b>__init__</b> function which enables you to determine all the parameters and layers you want. Second, it is the <b>forward</b> function which makes relation amongs all layers you have defined. Finally, you built the linearRegression model.

`Attention!! In this file we are building models, in the next tutorial we will learn how to build the training loop.`

In [7]:
import torch
import torch.nn as nn

class LinearReg(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(LinearReg, self).__init__()
        self.linear = nn.Linear(inputSize, outputSize)

    def forward(self, x):
        out = self.linear(x)
        return out


In [8]:
model=LinearReg(1,1)
model

LinearReg(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [9]:
from torch import FloatTensor
from torch.autograd import Variable  
model(FloatTensor([4]))

tensor([0.2035], grad_fn=<AddBackward0>)

# 2.Logistic Regression
Logistic Regression is very similar to Regression. We just need to add one sigmoid function after linear transformation of the resutls. If you want just build your model and do not use `the built-in Crossentropy` function. The model would be like below. However, if you will use 'built-in Crosssentropy' function, you can use the simple Regression model instead of Logistic Regression. The reason is that, the built-in Crosssentropy function use the unactivated value.

In [10]:
import torch
import torch.nn as nn

class LogisticReg(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(LogisticReg, self).__init__()
        #layers
        self.linear = nn.Linear(inputSize, outputSize)

        
        #activation functions
        self.sigmoid=nn.Sigmoid()
    def forward(self, x):
        out = self.linear(x)
        return self.sigmoid(out)


In [11]:
model=LogisticReg(3,4)
model

LogisticReg(
  (linear): Linear(in_features=3, out_features=4, bias=True)
  (sigmoid): Sigmoid()
)

In [12]:
Sample = torch.rand(5,3)
model(Sample)

tensor([[0.4655, 0.4006, 0.6527, 0.3259],
        [0.5602, 0.4533, 0.5481, 0.4358],
        [0.5782, 0.4029, 0.5316, 0.4494],
        [0.5937, 0.4574, 0.5036, 0.4898],
        [0.4947, 0.4248, 0.6338, 0.3311]], grad_fn=<SigmoidBackward>)

# 3.Artificial Neural Network
Neural Network(NN) is constructed from several layers. NN is one of the simplest application of deep learning. In deep learning model, we ask the model to discover the hidden features. In contrast, the machine learning algorithm the machine know the features. We can see one NN architecture below (image from google):

<img src='https://miro.medium.com/max/3000/1*HWhBextdDSkxYvz0kEMTVg.png' />

As it is clear, we have three layers with different activation function. So, as we explained it in the regression, we start to add as much as layer we want. The layers convert data from size= 784 (as input size)==> first hidden layer size=128 ==> second hidden layer size=64 ==> output size=10. In addition, you can add as much as layer you want in this way.

In [13]:
import torch
import torch.nn as nn

class NN(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(NN, self).__init__()
        #Hidden layers
        self.layer1 = nn.Linear(inputSize, 128)
        self.layer2 = nn.Linear(128, 64)
        
        #output layer
        self.layer3 = nn.Linear(64, outputSize)

        
        #activation functions
        self.relu=nn.ReLU()
        self.softmax=nn.Softmax(dim=1)
        
        
    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.relu(x)
        x = self.layer3(x)
        x = self.softmax(x)
        
        return x


In [14]:
model=NN(784,10)
model

NN(
  (layer1): Linear(in_features=784, out_features=128, bias=True)
  (layer2): Linear(in_features=128, out_features=64, bias=True)
  (layer3): Linear(in_features=64, out_features=10, bias=True)
  (relu): ReLU()
  (softmax): Softmax(dim=1)
)

In [15]:
Sample = torch.rand(5,784)
model(Sample)

tensor([[0.0989, 0.0938, 0.1007, 0.0976, 0.1053, 0.1091, 0.1055, 0.0919, 0.1007,
         0.0965],
        [0.0952, 0.0967, 0.1002, 0.0987, 0.1064, 0.1074, 0.1056, 0.0925, 0.0992,
         0.0980],
        [0.0943, 0.0948, 0.1052, 0.0984, 0.1044, 0.1089, 0.1034, 0.0910, 0.1013,
         0.0983],
        [0.0997, 0.0949, 0.1029, 0.0951, 0.1079, 0.1069, 0.1045, 0.0917, 0.1031,
         0.0934],
        [0.0966, 0.0947, 0.1021, 0.0974, 0.1028, 0.1110, 0.1028, 0.0945, 0.1018,
         0.0963]], grad_fn=<SoftmaxBackward>)

# 4.Recurrent Neural Network (RNN)
Recurrent Neural Network algorithms are trying to capture information in a series of samples. They are used in text prediction, translation, voice recognition, and time series forecasting. There exists several models type based on the application of Recurrent neural network. Here, we will focus only on the simplest recurrent network application, time series, and will discuss on others (e.g. NLP) in another tutorial. There are three main structurs for Recurrent Neural Network cells:1.RNN, 2.GRU, 3.LSTM. Here, we will explain how to build RNN and LSTM using built-in pytorch function. The goals of RNN structur is to use several previous steps to predict the several steps ahead. So we defines problem as :

<img src='Image/Time series problem defenition.PNG' />

The idea behinds Recurrent Neural Networks is to send inframtion from learning of the first elemnet in Sequence to the the last one. This feature is shown below as hidden states. 

<img src='Image/RNN.PNG' />


### Data input and output shape explanation

For all types of Recurrent Neural Network model, the input is the 3 dimentional matrix with (Batch Size, Sequence Length, Number of features) and output is the 3 dimentional matrix with (Batch Size, Sequence Length, Hidden_size). First, we will implement the RNN using the built-in library. Then we will build RNN model from the scratch with nn.module. Inside each RNN layer, there are several RNN cells with the number of sequence lenght. Inside each RNN cells, there are several neurons which define the hidden_size. For example, in image below (soruce:google): Number of features is 3 which are shown with orange circle, and number of neuraons (hidden_size) is 3 which are shown with blue circles. In RNN, there is two groups input for each cell, first, the input data from trainging sets, second, the hidden states. So, we need to define an initial hidden state. 


<img src='Image/Inside_RNN_cell.png' />


The oupput from RNN layer is the 3 dimentional matrix with (Batch Size, Sequence Length, Hidden_size). Based on the problem, we have to change this output. For example in time series forecasting, if we want to predict only the next time steps, we need an output shapes like (Batch Size, 1 , 1). So, we need to use the last output of the sequence, and using the linear layer to reduce Hidden_size to 1.  

## simple RNN

In [28]:
from torch.autograd import Variable
class RNN(nn.Module):
    def __init__(self, input_size, output_size, hidden_size, num_layer):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layer

        #Important Note: batch_first attribute means the first dimension in the Input data matrix is batch size and second one is the sequence length.
        self.rnn = nn.RNN(input_size, hidden_size, num_layer, batch_first=True)   
        self.linear = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        # initialize hidden state
        batch_size = x.size(0)
        hidden = self.init_hidden(batch_size)

        
        out, hidden = self.rnn(x, hidden)
        print('The output shape of all cells in the  sequence:')
        print(out.size())
        # Choosing the last rnn cells output
        out = out[:,-1,:]
        print('The output shape of last cell in the sequence:')
        print(out.size())
        out = self.linear(out)
        
        return out, hidden
    
    def init_hidden(self, batch_size):

        hidden = Variable(torch.zeros(self.num_layers, batch_size, self.hidden_size))
        return hidden

In [29]:
model=RNN(3,1,10,1)
model

RNN(
  (rnn): RNN(3, 10, batch_first=True)
  (linear): Linear(in_features=10, out_features=1, bias=True)
)

In [30]:
Sample = torch.rand(40,10,3)
out,hidden=model(Sample)

The output shape of all cells in the  sequence:
torch.Size([40, 10, 10])
The output shape of last cell in the sequence:
torch.Size([40, 10])


In [31]:
out.size()

torch.Size([40, 1])

In [32]:
hidden.size()

torch.Size([1, 40, 10])

## LSTM
LSTM is a gated recurrent neural network. If you are not familiar wit the structure of LSTM, please search in through the internet. To implement the LSTM, we just need to add initial cell state along with the hidden state.

In [44]:
from torch.autograd import Variable
class LSTM(nn.Module):
    def __init__(self, input_size, output_size, hidden_size, num_layer):
        super(LSTM, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layer

        #Important Note: batch_first attribute means the first dimension in the Input data matrix is batch size and second one is the sequence length.
        self.lstm = nn.LSTM(input_size, hidden_size, num_layer, batch_first=True)   
        self.linear = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        # initialize hidden state
        batch_size = x.size(0)
        hidden, cell = self.init_hidden(batch_size)

        
        out, (hidden,cell) = self.lstm(x, (hidden,cell))
        print('The output shape of all cells in the  sequence:')
        print(out.size())
        # Choosing the last rnn cells output
        out = out[:,-1,:]
        print('The output shape of last cell in the sequence:')
        print(out.size())
        out = self.linear(out)
        
        return out, (hidden,cell)
    
    def init_hidden(self, batch_size):

        hidden = Variable(torch.zeros(self.num_layers, batch_size, self.hidden_size))
        
        #add this line for LSTM
        cell = Variable(torch.zeros(self.num_layers, batch_size, self.hidden_size))
        return (hidden,cell)

In [45]:
model=LSTM(3,1,10,1)
model

LSTM(
  (lstm): LSTM(3, 10, batch_first=True)
  (linear): Linear(in_features=10, out_features=1, bias=True)
)

In [46]:
Sample = torch.rand(40,10,3)
out,(hidden,cell)=model(Sample)

The output shape of all cells in the  sequence:
torch.Size([40, 10, 10])
The output shape of last cell in the sequence:
torch.Size([40, 10])


In [47]:
out.size()

torch.Size([40, 1])

In [48]:
hidden.size()

torch.Size([1, 40, 10])

In [49]:
cell.size()

torch.Size([1, 40, 10])

# 5. Convoloution Neural Network (CNN)